@startuml

interface TreeCreator {
 +create(org: Organizer): AST
}

class ASTCreator implements TreeCreator {
 +create(org: Organizer): AST
 -createNode(token: Token): Node
}

' let x = 42;
'[Token(Declaration),Token(Identifier),Token(Assignment),Token(NumberLiteral),Token(Delimiter)]



@enduml