name: Java CI

on:
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 22
        uses: actions/setup-java@v1
        with:
          java-version: 22
      - name: Build with Gradle
        run: chmod +x ./gradlew
      - name: Check GITHUB envs (safe)
        run: |
          echo "GITHUB_ACTOR=$GITHUB_ACTOR"
          if [ -z "$GITHUB_TOKEN" ]; then
            echo "GITHUB_TOKEN is missing"
            exit 1
          else
            echo "GITHUB_TOKEN is set"
          fi
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish package
        run: gradle publish
        env:
          GITHUB_ACTOR: ${{ env.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}